### ISSUE TITLE
[BUG] App crashes after opening a photo

### ISSUE THREAD

**Issue by tarsonis123** [leonlatsch/Photok#147]
Updated today because of that but still the same. I can't view a picture in full size. Everything is alright in the gallery view. 
Android 11 here on MIUI 12.5. If I can provide something please ask.

**Comment by alxgnon** [comment]
This happens for me as well. It seems to happen for photos with an especially large resolution. It also happens randomly at some points. (?)

Usually when it happens to me, the app gets slower and slower to open pictures, until eventually, it crashes.

**Comment by leonlatsch** [comment]
Potential memory leak

**Comment by alxgnon** [comment]
@leonlatsch That's what I thought about it as well.

**Comment by TriStaRvOiD** [comment]
Once I had tried opening an image after import, Photok crashed.

Here's the log
https://www.toptal.com/developers/hastebin/pacehufile.properties

Something to do with the image being too large I believe.

**Comment by leonlatsch** [comment]
> 

The patebin is empty, please update this or post it here as a comment

**Comment by TriStaRvOiD** [comment]
> > 
> 
> The patebin is empty, please update this or post it here as a comment


FATAL EXCEPTION: main
Process: dev.leonlatsch.photok, PID: 29379
java.lang.RuntimeException: Canvas: trying to draw too large(176000000bytes) bitmap.
	at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:281)
	at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:91)
	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:548)
	at android.widget.ImageView.onDraw(ImageView.java:1453)
	at com.ortiz.touchview.TouchImageView.onDraw(TouchImageView.kt:284)
	at android.view.View.draw(View.java:23901)
	at android.view.View.updateDisplayListIfDirty(View.java:22776)
	at android.view.View.draw(View.java:23631)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1994)
	at android.view.View.draw(View.java:23904)
	at android.view.View.updateDisplayListIfDirty(View.java:22776)
	at android.view.View.draw(View.java:23631)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
	at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5204)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
	at android.view.View.draw(View.java:23904)
	at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4603)
	at android.view.View.updateDisplayListIfDirty(View.java:22776)
	at android.view.View.draw(View.java:23631)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
	at android.view.View.updateDisplayListIfDirty(View.java:22762)
	at android.view.View.draw(View.java:23631)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
	at android.view.View.draw(View.java:23904)
	at android.view.View.updateDisplayListIfDirty(View.java:22776)
	at android.view.View.draw(View.java:23631)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
	at androidx.fragment.app.FragmentContainerView.drawChild(FragmentContainerView.java:268)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
	at androidx.fragment.app.FragmentContainerView.dispatchDraw(FragmentContainerView.java:256)
	at android.view.View.updateDisplayListIfDirty(View.java:22762)
	at android.view.View.draw(View.java:23631)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
	at androidx.fragment.app.FragmentContainerView.drawChild(FragmentContainerView.java:268)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
	at androidx.fragment.app.FragmentContainerView.dispatchDraw(FragmentContainerView.java:256)
	at android.view.View.updateDisplayListIfDirty(View.java:22762)
	at android.view.View.draw(View.java:23631)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
	at android.view.View.updateDisplayListIfDirty(View.java:22762)
	at android.view.View.draw(View.java:23631)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1994)
	at android.view.View.updateDisplayListIfDirty(View.java:22762)
	at android.view.View.draw(View.java:23631)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
	at android.view.View.updateDisplayListIfDirty(View.java:22762)
	at android.view.View.draw(View.java:23631)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
	at android.view.View.updateDisplayListIfDirty(View.java:22762)
	at android.view.View.draw(View.java:23631)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
	at android.view.View.updateDisplayListIfDirty(View.java:22762)
	at android.view.View.draw(View.java:23631)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
	at android.view.View.updateDisplayListIfDirty(View.java:22762)
	at android.view.View.draw(View.java:23631)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
	at android.view.View.draw(View.java:23904)
	at com.android.internal.policy.DecorView.draw(DecorView.java:1284)
	at android.view.View.updateDisplayListIfDirty(View.java:22776)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:579)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:585)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:662)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5042)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4749)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3866)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2618)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9971)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
	at android.view.Choreographer.doCallbacks(Choreographer.java:809)
	at android.view.Choreographer.doFrame(Choreographer.java:744)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8595)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by TriStaRvOiD** [comment]
> > 
> 
> The patebin is empty, please update this or post it here as a comment

https://www.toptal.com/developers/hastebin/ubosukumaz.properties
